### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by layinka** [MarkerMetro/MarkerMetro.Unity.WinShared#119]
Hi,
I just tried adding this to a sample project and its failing to build.
I have run the Powerhell command.
When i then try building in either Unity or VS,i get the error 

*Error	2	Index (zero based) must be greater than or equal to zero and less than the size of the argument list.	C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v12.0\8.1\Microsoft.Windows.UI.Xaml.Common.targets	242	9	Test Marker Metro 2.Windows*

Please can you help out

**Comment by cedw032** [comment]
Hi Layinka

We would like to help you sort this out.

Are you able to provide us with a little more information?

Could you please let us know:

Which version of Unity are you using?
Which platform are you trying to build for from Unity?
Which OS are you using?
What version of Visual Studio are you using?

Are you able to send us a copy of the project to try to reproduce the problem?

Thanks,

Chad Edwards

chad.e@markermetro.com

**Comment by layinka** [comment]
**Which version of Unity are you using?** : Was 5.0.1 but just upgraded to Unity 5.0.2f1 now.
**Which platform are you trying to build for from Unity?** I am trying to build for Win Store Universal 8.1, both Win Phone and Windows
**Which OS are you using?** Windows 8.1
**What version of Visual Studio are you using?** VS 2013 update 4

I updated Unity this morning, and i am now getting error 
*Assets\MarkerMetro\Example\Scripts\GameMaster.cs(12,7): error CS0246: The type or namespace name 'LitJson' could not be found (are you missing a using directive or an assembly reference?) *

**Comment by robertocaldas** [comment]
Hi Layinka 

Thanks for your reply.
To fix the litjson error, please go to Plugins/Metro/LitJson.dll in Unity (please notice that there are 2 litjson dlls in the project) and set the _Placeholder_ to point to `Assets/Plugins/LitJson.dll`. This was working without the placeholder in Unity 5.0.0 but it seems they have changed it, we are fixing it in our side too.

Regarding the other error, it looks like our initialization script was never prepared to handle projects with space characters in the name, thanks for pointing that out :) Please try a name without spaces.

Finally, thanks for helping making WinShared better and let us know if that resolves the issues.

Regards,
Roberto

**Comment by layinka** [comment]
Thanks.
That fixed it all.

-----Original Message-----
